### ISSUE TITLE
Réservation BADGES

### ISSUE THREAD

**Issue by ar1bfs** [InfotelGLPI/badges#10]
Bonjour, j'ai récemment installé le plugin BADGES, pour pouvoir gérer les badges d'accès.
Donc je crée mes badges, je dis que les badges sont réservables.
Mais quand je vais dans l'onglet RESERVATION, mes badges n'apparaissent pas .... Donc je ne peux pas effectuer de réservation de badges ....

Merci d'avance

**Comment by tsmr** [comment]
Bonjour

En fait le système de réservation de badge ne fonctionne pas avec l'onglet réservation.

Il faut donner le droit de lecture sur les badges pour le profil self-service et dans le menu coté utilisateur, il y aura un lien dans le menu plugin pour faire des demandes de réservation de badge.

![image](https://cloud.githubusercontent.com/assets/13178158/20674542/ae3722f8-b589-11e6-8fbe-589d408d2efd.png)

**Comment by ar1bfs** [comment]
Merci beaucoup !!!! :)

Bonne soirée.
