### ISSUE TITLE
[GLPI 9.1.2] bug sur date de fin de validité

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/badges#11]
Bonjour
Dans la version 2.2.0, lorsque l'on veut modifier (pour un badge déjà enregistré) la valeur de champ date de fin de validité, si je vide le champ et que j'enregistre il me remet le contenu du champ.

**Comment by amma35** [comment]
Pour supprimer la date de fin de validité, avez-vous utilisé la croix ? 
C'est le seul moyen de vider un champ date.

![image](https://cloud.githubusercontent.com/assets/15138371/25065004/03049f1a-2207-11e7-8f7b-250327c318b5.png)

**Comment by sebfun** [comment]
de mémoire non
