### ISSUE TITLE
[GLPI 1.9.4] badges 2.2.0

### ISSUE THREAD

**Issue by sebfun** [InfotelGLPI/badges#12]
Bonjour

J'ai constaté avoir des erreurs SQL liées au plugin badges depuis que j'ai migré en GLPI 1.9.4, voici le log

> 2017-06-19 09:00:04 [@Serveur]
  *** MySQL query error:
  SQL: SELECT *
         FROM `glpi_plugin_badges_badges`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = \'0\'
         AND DATEDIFF(CURDATE(),`date_expiration`) > - 
         AND DATEDIFF(CURDATE(),`date_expiration`) < 0 AND `states_id` NOT IN (999999) 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND DATEDIFF(CURDATE(),`date_expiration`) < 0 AND `states_id` NOT IN (999999)' at line 6
  Backtrace :
  inc\dbmysql.class.php:872                          
  inc\dbmysql.class.php:558                          DBmysqlIterator->__construct()
  plugins\badges\inc\badge.class.php:441             DBmysql->request()
  :                                                  PluginBadgesBadge::cronBadgesAlert()
  inc\crontask.class.php:832                         call_user_func()
  front\cron.php:88                                  CronTask::launch()
2017-06-19 09:00:04 [@Serveur]
  *** MySQL query error:
  SQL: SELECT * 
         FROM `glpi_plugin_badges_badges`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = \'0\'
         AND DATEDIFF(CURDATE(),`date_expiration`) >  
         AND DATEDIFF(CURDATE(),`date_expiration`) > 0 AND `states_id` NOT IN (999999) 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND DATEDIFF(CURDATE(),`date_expiration`) > 0 AND `states_id` NOT IN (999999)' at line 6
  Backtrace :
  inc\dbmysql.class.php:872                          
  inc\dbmysql.class.php:558                          DBmysqlIterator->__construct()
  plugins\badges\inc\badge.class.php:441             DBmysql->request()
  :                                                  PluginBadgesBadge::cronBadgesAlert()
  inc\crontask.class.php:832                         call_user_func()
  front\cron.php:88                                  CronTask::launch()

**Comment by amma35** [comment]
Bonjour,

Dans la configuration de l'action automatique, y'a t-il toujours les délais ?
Dans les erreurs SQL, il ne récupère pas les différents délais. 

Car je viens d'effectuer le test avec la version GLPi 9.1.4, je n'ai pas eu de problème la configuration de l'action automatique est toujours présente et je n'obtiens pas d'erreurs SQL.

**Comment by sebfun** [comment]
Voici les valeurs : 
 	BadgesAlert 	Badge 	Badges qui vont expirer 	Programmée 	19-06-2017 09:00 	CLI 	1 jours 0 heures 0 minutes 	0 	24
 
	BadgesReturnAlert 	Retourner un badge 	Retourner un badge 	Programmée 	19-06-2017 09:10 	CLI 	1 jours 0 heures 0 minutes 	0 	24

**Comment by amma35** [comment]
La configuration de l'action automatique pour indiquer les délais s'effectue dans l'onglet "Configuration du plugin" : 
![2017-06-19 11_41_39-glpi - actions automatiques - 21](https://user-images.githubusercontent.com/15138371/27279225-4dc0e03a-54e4-11e7-9e42-671c35f5577b.png)

**Comment by sebfun** [comment]
Dans BadgesAlert configuration du plugin il n'y a rien inscrit. J'ai ajouté les valeurs à titre d'exemples (les vôtres) et il n'y a toujours rien d'inscrit quand je fais sauvegarder
Par contre les status non utilisés dans l'envoi de mail d'expiration sont bien conservés quand j'en ajoute.

**Comment by amma35** [comment]
Vous avez du avoir de nouvelles erreurs SQL suite à votre sauvegarde ?

**Comment by sebfun** [comment]
j'ai regardé dans SQL-errors.log pas de nouvelle erreur

**Comment by amma35** [comment]
Pouvez-vous consulter le contenu de la table `glpi_plugin_badges_configs` ?

**Comment by sebfun** [comment]
MySQL a retourné un résultat vide (aucune ligne). (Traitement en 0.0000 secondes.)

**Comment by amma35** [comment]
C'est pour ça que cela ne fonctionne plus. 
Lors de la migration, cette table n'a pas du bien migré.

Si la table existe il faudrait lancer  cette requete : 
`INSERT INTO `glpi_plugin_badges_configs` VALUES (1, '30', '30', '30');`

Si la table n'existe pas : 
`DROP TABLE IF EXISTS `glpi_plugin_badges_configs`;
CREATE TABLE `glpi_plugin_badges_configs` (
   `id` int(11) NOT NULL auto_increment,
   `delay_expired` varchar(50) collate utf8_unicode_ci NOT NULL default '30',
   `delay_whichexpire` varchar(50) collate utf8_unicode_ci NOT NULL default '30',
   `delay_returnexpire` int(11) NOT NULL default '0',
   PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
INSERT INTO `glpi_plugin_badges_configs` VALUES (1, '30', '30', '30');`

**Comment by sebfun** [comment]
C'est ok je confirme ça fonctionne car j'ai remodifié les valeurs après l'INSERT et il me les a bien gardé. :)
merci
Je ferme cette demande

**Comment by sebfun** [comment]
par contre il y a 3 valeurs dans votre insert alors que je n'en saisis que 2 depuis la configuration du plugin, est-ce normal ?
