### ISSUE TITLE
Badge request

### ISSUE THREAD

**Issue by Miminoux** [InfotelGLPI/badges#13]
Hi,

This is not a properly named "bug" but I can't find the way for a badge request. 
I don't know what I have to activate in order to let a user ask for a new badge.
Of course, I might end up ask them to open a new ticket claiming for a badge but as I can read "Badge requests" when watching a badge details, I'm curious. 

And anyway, thanks a lot for the plugin, it is very useful. 

Bye bye

**Comment by amma35** [comment]
Hi,

For simplified interface profiles, via the "Plugin> Badges" menu.
Two wizards are present "Access badge request" and "Return an access badge".

![menu](https://user-images.githubusercontent.com/15138371/35087074-c9e2cb62-fc26-11e7-84bb-d1a5237c38c3.png)

**Comment by Miminoux** [comment]
Well,
I don't have this menu, can you tell me what profile setting are required please ?
Bye bye

**Comment by Miminoux** [comment]
Ok, I found it : the profile needs the read access on badges.

Thanks

**Comment by Miminoux** [comment]
So bad, I closed the issue a bit too fast...
The request implies 5 fields : name, firstname, company, arrival date and **available badges** ?
What is the point of "available badges" ? If I want a badge, I don't care which one, I just want one. Or at least, I could specify the badge type or some requirement about the badge.
Can you provide me some clue about this field please ?

Bye bye

**Comment by Miminoux** [comment]
I forgot to tell something, I can't see any badge in the dropdown list.
The same with the badge return form, I don't see my badge.
What have I done wrong ?

**Comment by Miminoux** [comment]
Last question (for now ahaha) : why have you chosen to limit badge request/return forms to simplified profiles ?

**Comment by amma35** [comment]
This functionality is a customer request. 
For a temporary badge request, the badge must be bookable.

**Comment by amma35** [comment]
I'm closing for now, you can contact us to make a development request.
