### ISSUE TITLE
Problem with sub-entity

### ISSUE THREAD

**Issue by Vutman** [InfotelGLPI/badges#14]
Hello,

- The version of the plugin. => 2.3.0
- The version of your GLPI => 9.2.1

I cannot add a badge to a user if the user has only one profile on a sub-entity.
I can only add a badge if the user has a profile on root entity.

When adding a new badge, the user doesn't appear in the drop-down menu.

Am I missing something ?

Thanks,

**Comment by amma35** [comment]
Hi,

Badges are not recursive if users are present in sub entities they will not be visible in the badge interface. 

It would take dedicated development to add recursivity to the badges.

**Comment by Vutman** [comment]
Hi,

thanks for your answer.

Is it planned on your roadmap ? Because without recursivity we can't manage
multi entity for our users.

Thanks,

Cordialement,

*Vuthy TAN*
*01 80 98 05 05*

2018-03-28 15:27 GMT+02:00 Amandine Manceau <notifications@github.com>:

**Comment by amma35** [comment]
At this time, this change is not planned.

**Comment by amma35** [comment]
Fix in 6de58e1

**Comment by C-Duv** [comment]
It looks like it's not working anymore (at least on v2.6.0 on GLPI v9.5): I do have the `is_recursive` SQL field and the "Child entities" drop-down selector on badge's page.
But I still cannot associate a badge to a user from a child entity: only users from the same entity as the badge are listed in the drop-down selector.
