### ISSUE TITLE
This plugin requires GLPI > 9.3.

### ISSUE THREAD

**Issue by rcfloresh** [InfotelGLPI/badges#15]
------------
* Version of the plugin : 

* Version of your GLPI : 
**9.2.3**

* Steps to reproduce (which actions have you made) :
When I try to install the plugins, show the message, that is only available higher 9.3 but the last GLPI version is 9.2.3

**Comment by amma35** [comment]
Which version of the plugin?

**Comment by amma35** [comment]
This is normal the master branch is a development branch which is in GLPI 9.3.

You have to download the releases.
