### ISSUE TITLE
Installation plugin badge on glpi 0.90

### ISSUE THREAD

**Issue by satyan01** [InfotelGLPI/badges#5]
The plugin appears but the error message as well when I start install.a

Incorrect integer value: '' for column 'id' at row 1

**Comment by tsmr** [comment]
Already corrected
https://github.com/InfotelGLPI/badges/issues/4

**Comment by satyan01** [comment]
With last master GLPI 0.90 and Last master Badge I have the bug. New try this morning after your message and it is always the same.

**Comment by tsmr** [comment]
Can you give me the sql or php-error ?

**Comment by satyan01** [comment]
where can I find this error ?

**Comment by tsmr** [comment]
glpi/files/_log

**Comment by satyan01** [comment]
2015-11-19 10:06:21 [854@UNGSRVGVA117]
  *** MySQL query error:
  SQL: INSERT INTO `glpi_notificationtemplates`(`id`, `name`, `itemtype`, `date_mod`, `comment`, `css`) VALUES (\'\',\'Access Badges Return\',\'PluginBadgesBadge\', NOW(),\'\',\'\');
  Error: Incorrect integer value: '' for column 'id' at row 1
  Backtrace :
  plugins\badges\hook.php:130                        
  inc\plugin.class.php:643                           plugin_badges_install()
  :                                                  Plugin->install()
  front\plugin.form.php:49                           call_user_func()

**Comment by satyan01** [comment]
Confirmed. bug has been fixed with your modifications. Thank you very much. Good job !
