### ISSUE TITLE
Erreur SQL

### ISSUE THREAD

**Issue by monpelaud** [InfotelGLPI/badges#6]
Bonjour,

Version utilisée:
- CentOS 7
- GLPI 0.90.1
- Plugin Badges for GLPI 2.1.1

Dans les logs GLPI le plugin Badges génère l'erreur SQL suivante:

  *** MySQL query error:
  SQL: SELECT *
         FROM `glpi_plugin_badges_badges`
         WHERE `date_expiration` IS NOT NULL
         AND `is_deleted` = \'0\'
         AND DATEDIFF(CURDATE(),`date_expiration`) >
         AND DATEDIFF(CURDATE(),`date_expiration`) > 0 AND `states_id` NOT IN (999999)
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to
use near 'AND DATEDIFF(CURDATE(),`date_expiration`) > 0 AND `states_id` NOT IN (999999)' at line 6

Cordialement

**Comment by tsmr** [comment]
Pouvez-vous me donner le contenu de la table : glpi_plugin_badges_configs ?

**Comment by monpelaud** [comment]
Je viens juste d'installer le plugin, la table glpi_plugin_badges_configs est vide.

**Comment by tsmr** [comment]
pas d'erreurs sql ? car il aurait du ajouter des infos dedans

**Comment by monpelaud** [comment]
Voici le résultats de la requête: SELECT * FROM `glpi_plugin_badges_configs`
MySQL a retourné un résultat vide (aucune ligne).

**Comment by tsmr** [comment]
mais dans /glpi/files/_log/sql-errors.log ?

**Comment by monpelaud** [comment]
Dans le fichier /glpi/files/_log/sql-errors.log je trouve l'erreur sql que j'ai remontée au début de ce ticket plus l'erreur ci-dessous:

  *** MySQL query error:
  SQL: SELECT *
                         FROM `glpi_profiles` WHERE  (`glpi_profiles`.`interface` = \'helpdesk\')  OR (`glpi_profiles`.`interface` = \'central\'  AND 102 = (
                    SELECT count(*)
                    FROM `glpi_profilerights`
                    WHERE `glpi_profilerights`.`profiles_id` = `glpi_profiles`.`id`
                     AND ((`glpi_profilerights`.`name` = \'backup\'
                                   AND (`glpi_profilerights`.`rights` | 1024) = 1024) OR (`glpi_profilerights`.`name` = \'bookmark_public\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'budget\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'calendar\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'cartridge\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'change\'
                                   AND (`glpi_profilerights`.`rights` | 1151) = 1151) OR (`glpi_profilerights`.`name` = \'changevalidation\'
                                   AND (`glpi_profilerights`.`rights` | 1044) = 1044) OR (`glpi_profilerights`.`name` = \'computer\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'config\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'consumable\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'contact_enterprise\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'contract\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'device\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'document\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'domain\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'dropdown\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'entity\'
                                   AND (`glpi_profilerights`.`rights` | 96) = 96) OR (`glpi_profilerights`.`name` = \'followup\'
                                   AND (`glpi_profilerights`.`rights` | 15383) = 15383) OR (`glpi_profilerights`.`name` = \'group\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'infocom\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'internet\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'itilcategory\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'knowbase\'
                                   AND (`glpi_profilerights`.`rights` | 6175) = 6175) OR (`glpi_profilerights`.`name` = \'knowbasecategory\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'link\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'location\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'logs\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'monitor\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'netpoint\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'networking\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'notification\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'password_update\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'peripheral\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'phone\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'planning\'
                                   AND (`glpi_profilerights`.`rights` | 3073) = 3073) OR (`glpi_profilerights`.`name` = \'plugin_badges\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'plugin_badges_open_ticket\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'plugin_certificates\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'plugin_certificates_open_ticket\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'printer\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'problem\'
                                   AND (`glpi_profilerights`.`rights` | 1151) = 1151) OR (`glpi_profilerights`.`name` = \'profile\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'project\'
                                   AND (`glpi_profilerights`.`rights` | 1151) = 1151) OR (`glpi_profilerights`.`name` = \'projecttask\'
                                   AND (`glpi_profilerights`.`rights` | 1025) = 1025) OR (`glpi_profilerights`.`name` = \'queuedmail\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'reminder_public\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'reports\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'reservation\'
                                   AND (`glpi_profilerights`.`rights` | 1055) = 1055) OR (`glpi_profilerights`.`name` = \'rssfeed_public\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'rule_dictionnary_dropdown\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_dictionnary_printer\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_dictionnary_software\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_import\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_ldap\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_mailcollector\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_softwarecategories\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'rule_ticket\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'search_config\'
                                   AND (`glpi_profilerights`.`rights` | 3103) = 3103) OR (`glpi_profilerights`.`name` = \'show_group_hardware\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'sla\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'software\'
                                   AND (`glpi_profilerights`.`rights` | 127) = 127) OR (`glpi_profilerights`.`name` = \'solutiontemplate\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'state\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'statistic\'
                                   AND (`glpi_profilerights`.`rights` | 1) = 1) OR (`glpi_profilerights`.`name` = \'task\'
                                   AND (`glpi_profilerights`.`rights` | 13329) = 13329) OR (`glpi_profilerights`.`name` = \'taskcategory\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'ticket\'
                                   AND (`glpi_profilerights`.`rights` | 128031) = 128031) OR (`glpi_profilerights`.`name` = \'ticketcost\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'ticketrecurrent\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'tickettemplate\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'ticketvalidation\'
                                   AND (`glpi_profilerights`.`rights` | 15384) = 15384) OR (`glpi_profilerights`.`name` = \'transfer\'
                                   AND (`glpi_profilerights`.`rights` | 0) = 0) OR (`glpi_profilerights`.`name` = \'typedoc\'
                                   AND (`glpi_profilerights`.`rights` | 31) = 31) OR (`glpi_profilerights`.`name` = \'user\'
                                   AND (`glpi_profilerights`.`rights` | 7199) = 7199) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_agent\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_blacklist\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_collect\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_configsecurity\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_configuration\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_credential\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_credentialip\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_deploymirror\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_esx\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_group\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_importxml\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_iprange\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_lock\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_menu\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_networkequipment\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_package\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_printer\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_remotecontrol\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_reportnetworkequipment\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_reportprinter\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_rulecollect\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_ruleentity\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_ruleimport\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_rulelocation\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_status\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_task\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_unmanaged\'
                                   AND (`glpi_profilerights`.`rights` | ) = ) OR (`glpi_profilerights`.`name` = \'plugin_fusioninventory_wol\'
                                   AND (`glpi_profilerights`.`rights` | ) = ))))
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') = ) OR (`glpi_profil
erights`.`name` = 'plugin_fusioninventory_blacklist'
     ' at line 81
  Backtrace :
  inc/profile.class.php:507
  inc/user.class.php:1805                            Profile::currentUserHaveMoreRightThan()
  inc/config.class.php:1682                          User->currentUserHaveMoreRightThan()
  inc/commonglpi.class.php:208                       Config->getTabNameForItem()
  inc/user.class.php:247                             CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:158                       User->defineTabs()
  inc/commonglpi.class.php:689                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1124                      CommonGLPI->showTabsContent()
  front/user.form.php:180                            CommonGLPI->display()

**Comment by tsmr** [comment]
Non lié à ton souci : 

tu pourrais exécuter cette requête sur ta DB : 
```
INSERT INTO `glpi_plugin_badges_configs` VALUES (1, '30', '30', '30');
```
Ça devrait résoudre ton problème

**Comment by monpelaud** [comment]
Après avoir passé la requête pas de nouvelle erreur dans les logs pour l'instant.
Comme je ne sais pas par quelle action précise l'erreur était produite je vais surveiller les logs.
Je clos le ticket.

Merci pour ton aide.
Cordialement
