### ISSUE TITLE
Insert non exécutés à l'installation et à l'activation du plugin

### ISSUE THREAD

**Issue by monpelaud** [InfotelGLPI/badges#7]
Bonjour,
Après installation et activation du plugin "Badges" les 4 INSERT suivants du fichier "badges/sql/empty-2.0.1.sql" n'ont pas été exécutés:

INSERT INTO `glpi_plugin_badges_configs` VALUES (1, '30', '30', '30');
INSERT INTO `glpi_notificationtemplates` VALUES(NULL, 'Alert Badges', 'PluginBadgesBadge', '2010-02-23 23:44:46','',NULL);
INSERT INTO `glpi_displaypreferences` VALUES (NULL,'PluginBadgesBadge','3','2','0');
INSERT INTO `glpi_displaypreferences` VALUES (NULL,'PluginBadgesBadge','4','3','0');
INSERT INTO `glpi_displaypreferences` VALUES (NULL,'PluginBadgesBadge','5','4','0');

J'ai exécuté manuellement le premier INSERT dans `glpi_plugin_badges_configs` sinon j'obtenais un message d'erreur.
Les 4 autres INSERT sont-ils nécessaires au bon fonctionnement du plugin?
Quel est leur rôle?
Dois-je les exécuter manuellement?

Cordialement

**Comment by sebfun** [comment]
à ma connaissance le plugin est automatiquement installé, il n'y a pas d'action manuelle à faire.
Quelle est la version de votre GLPI  et quelle version du plugin installez-vous ? Mise à jour ou nouvelle installation du plugin ?

**Comment by monpelaud** [comment]
Bonjour,
Merci pour votre réponse.
Il s'agit d'une première installation.
Version utilisée à l'installation:
- CentOS 7
- GLPI 0.90.1 puis 0.90.5
- Plugin Badges for GLPI 2.1.1

Cordialement

**Comment by amma35** [comment]
Bonjour,
Le rôle des autres INSERT sont : 
glpi_notificationtemplates : ajoute un modèle de notification.
glpi_displaypreferences : ajoute des colonnes lors de l'affichage de la liste des badges lors de l'installation. Au lieu d'avoir seulement le nom du badge, il y a d'autres colonnes d'ajoutés.
Cela a été corrigé dans la nouvelle version.

**Comment by monpelaud** [comment]
Bonjour,
Merci beaucoup pour votre réponse.
Je vais mettre à jour ma version du plugin.

Cordialement
