### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by sulian** [InfotelGLPI/badges#8]
With GLPI 0.95 and simcard plugin v2.1.1, I cannot install the plugin : error during installation

``
2016-10-28 11:23:44 [6@linux01]
  **\* MySQL query error:
  SQL: INSERT INTO 'glpi_notificationtemplates'('id', 'name', 'itemtype', 'date_mod', 'comment', 'css') VALUES (\'\',\'Access Badges Return\',\'PluginBadgesBadge\', NOW(),\'\',\'\');

  Error: Incorrect integer value: '' for column 'id' at row 1
  Backtrace :
  plugins/badges/hook.php:130  
  inc/plugin.class.php:661                           plugin_badges_install()
  :                                                  Plugin->install()
  front/plugin.form.php:49                           call_user_func()
``

I have bypassed the problem by edit `hook.php`, line 130 : 

`
$query_id = "INSERT INTO `glpi_notificationtemplates`(`name`, `itemtype`, `date_mod`, `comment`, `css`) VALUES ('Access Badges Return','PluginBadgesBadge', NOW(),'','');";
`

Seems to be an old bug already resolved but back again...

**Comment by sebfun** [comment]
Was it an upgrade or a new installation of the plugin ?

**Comment by sulian** [comment]
New installation
